/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndkdemo_JNITest */

#ifndef _Included_com_example_ndkdemo_JNITest
#define _Included_com_example_ndkdemo_JNITest
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_ndkdemo_JNITest
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_ndkdemo_JNITest_sum
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_ndkdemo_JNITest
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndkdemo_JNITest_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
